import {test} from 'node:test';import assert from 'node:assert/strict';
import {progressoAdmissao,dataLocalAdmissao,normalizarFormAdmissao,aplicarPerfilAdmissao,validarArquivoAdmissao} from './admissao.ts';
import {legacyPath} from '../../scripts/migrar-documentos-admissao.mjs';
test('progresso conta validados, não apenas recebidos, excluindo não aplicáveis',()=>{assert.equal(progressoAdmissao([{status:'recebido'},{status:'validado'},{status:'na'}]),50);});
test('formulário não escreve ou limpa URLs de anexos legados',()=>{assert.equal('documentos_urls' in normalizarFormAdmissao({documentos_urls:['original']}),false);});
test('modelo não transfere validações nem exclui requisitos existentes',()=>{const d=aplicarPerfilAdmissao({requisitos:[{id:'a',status:'validado'}],treinamentos_exigidos:[],epis_exigidos:[]},{nome:'Modelo',requisitos:[{id:'b',nome:'Novo',area:'sms',status:'validado',arquivo_id:'outro'}],treinamentos:['t'],epis:[]});assert.equal(d.requisitos[0].status,'validado');assert.equal(d.requisitos[1].status,'pendente');assert.equal(d.requisitos[1].arquivo_id,undefined);});
test('data usa calendário local',()=>assert.equal(dataLocalAdmissao(new Date(2026,7,31,23,59)),'2026-08-31'));
test('uploads limitam formato e tamanho',()=>{assert.equal(validarArquivoAdmissao({type:'application/pdf',size:100}),'pdf');assert.throws(()=>validarArquivoAdmissao({type:'text/html',size:100}));assert.throws(()=>validarArquivoAdmissao({type:'application/pdf',size:11*1024*1024}));});
test('migração aceita somente origem configurada e pasta admissao',()=>{const base='https://test.invalid';assert.equal(legacyPath(base+'/storage/v1/object/public/sms-midias/admissao/a.pdf',base),'admissao/a.pdf');assert.throws(()=>legacyPath('https://other.invalid/storage/v1/object/public/sms-midias/admissao/a.pdf',base));assert.throws(()=>legacyPath(base+'/storage/v1/object/public/sms-midias/dds/a.pdf',base));assert.throws(()=>legacyPath(base+'/storage/v1/object/public/sms-midias/admissao/%2e%2e%2fa.pdf',base));});
