import {useCallback,useEffect,useRef,useState} from 'react'
import {supabase} from './supabaseClient'
type ScreenState='scanning'|'consulting'|'choosing'|'saving'|'confirmed'|'error'
type PunchEvent='entrada'|'intervalo_saida'|'intervalo_retorno'|'saida'
type Employee={employee_id:string;nome:string;foto_url:string|null;cargo:string;eventos:PunchEvent[]}
type Confirmation=Employee&{tipo:'entrada'|'saida';evento:PunchEvent;registrado_em:string;totem:string}
const QR=/^APICE:1:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
const labels:Record<PunchEvent,string>={entrada:'Iniciar jornada',intervalo_saida:'Iniciar intervalo',intervalo_retorno:'Retornar do intervalo',saida:'Encerrar jornada'}
const icons:Record<PunchEvent,string>={entrada:'▶',intervalo_saida:'☕',intervalo_retorno:'↩',saida:'■'}

export function TotemScreen({deviceId,deviceSecret,appVersion}:{deviceId:string;deviceSecret:string;appVersion:string}){
 const [state,setState]=useState<ScreenState>('scanning'),[employee,setEmployee]=useState<Employee|null>(null),[confirmation,setConfirmation]=useState<Confirmation|null>(null),[error,setError]=useState(''),[clock,setClock]=useState(now()),[online,setOnline]=useState(navigator.onLine)
 const scanner=useRef<any>(null),mounted=useRef(true),locked=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),qr=useRef(''),startRef=useRef<()=>Promise<void>>(async()=>{}),stateRef=useRef<ScreenState>('scanning')
 stateRef.current=state
 const stop=useCallback(async()=>{if(scanner.current){try{await scanner.current.stop()}catch{scanner.current=null}try{scanner.current?.clear()}catch{scanner.current=null}scanner.current=null}},[])
 const reset=useCallback(async()=>{if(!mounted.current)return;if(timer.current)clearTimeout(timer.current);setEmployee(null);setConfirmation(null);setError('');setState('scanning');locked.current=false;qr.current='';await startRef.current()},[])
 const fail=useCallback((message:string,auto=true)=>{if(!mounted.current)return;setError(friendly(message));setState('error');beep(false);if(timer.current)clearTimeout(timer.current);if(auto)timer.current=setTimeout(reset,5000)},[reset])
 const consult=useCallback(async(token:string)=>{setState('consulting');try{const {data,error}=await withTimeout<any>((supabase as any).rpc('consultar_ponto_totem',{p_cracha:token,p_device:deviceId,p_secret:deviceSecret,p_version:appVersion}),12000);if(error)throw error;if(!mounted.current)return;qr.current=token;setEmployee(data);setState('choosing');beep(true)}catch(e:any){fail(e?.message||'Falha ao consultar o crachá')}},[appVersion,deviceId,deviceSecret,fail])
 const start=useCallback(async()=>{if(!mounted.current)return;if(!navigator.onLine){fail('Totem sem conexão. Nenhum ponto foi registrado.');return}try{await stop();const {Html5Qrcode}=await import('html5-qrcode');const instance=new Html5Qrcode('totem-reader');scanner.current=instance;await instance.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},async(decoded:string)=>{if(locked.current)return;locked.current=true;await stop();const token=decoded.trim();if(!QR.test(token)){fail('Crachá inválido ou desatualizado. Procure o responsável.');return}await consult(token)},()=>{})}catch{fail('Câmera indisponível. Verifique a permissão e tente novamente.')}},[consult,fail,stop]);startRef.current=start
 useEffect(()=>{mounted.current=true;start();const tick=setInterval(()=>setClock(now()),10000),on=()=>setOnline(true),off=()=>setOnline(false),visibility=()=>{if(document.hidden)stop();else if(stateRef.current==='scanning')startRef.current()};addEventListener('online',on);addEventListener('offline',off);document.addEventListener('visibilitychange',visibility);return()=>{mounted.current=false;if(timer.current)clearTimeout(timer.current);clearInterval(tick);removeEventListener('online',on);removeEventListener('offline',off);document.removeEventListener('visibilitychange',visibility);stop()}},[])
 async function save(event:PunchEvent){if(!employee||state==='saving')return;setState('saving');try{const {data,error}=await withTimeout<any>((supabase as any).rpc('registrar_ponto_totem',{p_cracha:qr.current,p_device:deviceId,p_secret:deviceSecret,p_evento:event,p_version:appVersion}),12000);if(error)throw error;setConfirmation(data);setState('confirmed');beep(true);timer.current=setTimeout(reset,5500)}catch(e:any){if(/Tempo de resposta/.test(e?.message||''))fail('Resposta do servidor incerta. Não registre novamente. Procure o responsável para conferir o painel.',false);else fail(e?.message||'Não foi possível registrar')}}
 return <main className="totem"><header><b>ÁPICE GESTÃO</b><span>Registro de ponto · {clock}</span><i className={online?'online':'offline'}>{online?'Online':'Offline'}</i></header><section className="camera"><div id="totem-reader"/>{state==='scanning'&&<div className="hint"><b>Apresente o QR Code do crachá</b><span>Aguarde a identificação</span></div>}{['consulting','saving'].includes(state)&&<Overlay><div className="spinner"/><b>{state==='saving'?'Registrando no servidor…':'Identificando crachá…'}</b></Overlay>}{state==='choosing'&&employee&&<Overlay><Person data={employee}/><h2>O que deseja registrar?</h2><div className="events">{employee.eventos.map(e=><button key={e} onClick={()=>save(e)}><strong>{icons[e]}</strong>{labels[e]}</button>)}</div>{!employee.eventos.length&&<><p>Jornada encerrada hoje.</p><button className="secondary" onClick={reset}>Próximo crachá</button></>}</Overlay>}{state==='confirmed'&&confirmation&&<Overlay className="success"><div className="check">✓</div><Person data={confirmation}/><h1>{labels[confirmation.evento]}</h1><time>{serverTime(confirmation.registrado_em)}</time><span>Horário confirmado pelo servidor · {confirmation.totem}</span></Overlay>}{state==='error'&&<Overlay className="failure"><div className="cross">×</div><h2>{error}</h2><button onClick={reset}>Tentar novamente</button></Overlay>}</section><footer>Totem {deviceId.slice(0,8)} · versão {appVersion}</footer></main>
}
function Overlay({children,className=''}:{children:React.ReactNode;className?:string}){return <div className={'overlay '+className}>{children}</div>}
function Person({data}:{data:{nome:string;foto_url:string|null;cargo:string}}){const initials=data.nome.split(' ').map(n=>n[0]).join('').slice(0,2);return <div className="person">{data.foto_url?<img src={data.foto_url} alt="Foto do funcionário"/>:<div>{initials}</div>}<b>{data.nome}</b><span>{data.cargo}</span></div>}
function now(){return new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function serverTime(iso:string){return new Date(iso).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function friendly(s:string){if(/Failed to fetch|NetworkError|fetch/i.test(s))return'Totem sem comunicação com o servidor. Nenhum ponto foi registrado.';return s.replace(/^.*?message[: ]*/i,'').slice(0,180)}
function withTimeout<T>(promise:Promise<T>,ms:number){return Promise.race([promise,new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error('Tempo de resposta excedido. Verifique a internet.')),ms))])}
function beep(ok:boolean){try{const C=window.AudioContext||(window as any).webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?880:220;g.gain.value=.08;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.14)}catch{return}}
