import { useCallback, useEffect, useMemo, useState } from "react";
import { Layout } from "@/components/layout/Layout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/i18n";
import { Download, Eye, RefreshCw, Search, ShieldCheck, UserCheck, LogIn, Activity } from "lucide-react";
import { toast } from "sonner";

type AuditRow = { id:number; ocorrido_em:string; usuario_id:string|null; usuario_nome:string|null; usuario_email:string|null; usuario_perfil:string|null; acao:string; modulo:string; tabela:string|null; registro_id:string|null; obra_id:string|null; origem:string; ip:string|null; user_agent:string|null; dados_anteriores:unknown; dados_novos:unknown };
const isoDay=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)};
const actionTone:Record<string,string>={LOGIN:"bg-emerald-100 text-emerald-800",LOGOUT:"bg-slate-100 text-slate-700",INSERT:"bg-blue-100 text-blue-800",UPDATE:"bg-amber-100 text-amber-800",DELETE:"bg-red-100 text-red-800",DENIED:"bg-red-100 text-red-800"};

export default function Auditoria(){
  const {t,date}=useI18n();
  const [rows,setRows]=useState<AuditRow[]>([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState<AuditRow|null>(null);
  const [inicio,setInicio]=useState(isoDay(-30)),[fim,setFim]=useState(isoDay()),[usuario,setUsuario]=useState(""),[acao,setAcao]=useState("todos"),[modulo,setModulo]=useState("todos");
  const load=useCallback(async()=>{setLoading(true);const{data,error}=await(supabase as any).rpc("listar_auditoria",{p_inicio:`${inicio}T00:00:00`,p_fim:`${fim}T23:59:59.999`,p_usuario:usuario||null,p_modulo:modulo==="todos"?null:modulo,p_acao:acao==="todos"?null:acao,p_limite:500});setLoading(false);if(error){toast.error(error.message);return}setRows(data??[])},[inicio,fim,usuario,acao,modulo]);
  useEffect(()=>{load()},[load]);
  const modules=useMemo(()=>Array.from(new Set(rows.map(r=>r.modulo))).sort(),[rows]);
  const logins=rows.filter(r=>r.acao==="LOGIN").length,changes=rows.filter(r=>["INSERT","UPDATE","DELETE"].includes(r.acao)).length,users=new Set(rows.map(r=>r.usuario_id??r.usuario_email).filter(Boolean)).size;
  const exportCsv=()=>{const head=["Data/hora","Usuário","E-mail","Perfil","Ação","Módulo","Registro","Origem","IP"];const lines=[head,...rows.map(r=>[new Date(r.ocorrido_em).toLocaleString(),r.usuario_nome??"",r.usuario_email??"",r.usuario_perfil??"",r.acao,r.modulo,r.registro_id??"",r.origem,r.ip??""])];const csv="\ufeff"+lines.map(x=>x.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`auditoria-${inicio}-${fim}.csv`;a.click();URL.revokeObjectURL(a.href)};
  return <Layout><div className="mx-auto max-w-screen-2xl space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="h-6 w-6 text-primary"/>{t("Auditoria do Sistema")}</h1><p className="text-sm text-muted-foreground">{t("Rastreabilidade de acessos e operações realizadas pelos usuários.")}</p></div><div className="flex gap-2"><Button variant="outline" onClick={load}><RefreshCw className="mr-2 h-4 w-4"/>{t("Atualizar")}</Button><Button variant="outline" disabled={!rows.length} onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>{t("Exportar CSV")}</Button></div></div>
    <div className="grid gap-3 md:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-4"><LogIn className="h-8 w-8 text-emerald-600"/><div><p className="text-xs text-muted-foreground">{t("Entradas no período")}</p><p className="text-2xl font-bold">{logins}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><Activity className="h-8 w-8 text-blue-600"/><div><p className="text-xs text-muted-foreground">{t("Alterações registradas")}</p><p className="text-2xl font-bold">{changes}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><UserCheck className="h-8 w-8 text-violet-600"/><div><p className="text-xs text-muted-foreground">{t("Usuários ativos")}</p><p className="text-2xl font-bold">{users}</p></div></CardContent></Card></div>
    <Card><CardContent className="p-4"><div className="flex flex-wrap gap-2"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" placeholder={t("Buscar usuário ou e-mail...")} value={usuario} onChange={e=>setUsuario(e.target.value)}/></div><Input type="date" className="w-40" value={inicio} onChange={e=>setInicio(e.target.value)}/><Input type="date" className="w-40" value={fim} onChange={e=>setFim(e.target.value)}/><Select value={acao} onValueChange={setAcao}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="todos">{t("Todas as ações")}</SelectItem>{["LOGIN","LOGOUT","INSERT","UPDATE","DELETE","EXPORT","ACCESS","DENIED"].map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={modulo} onValueChange={setModulo}><SelectTrigger className="w-52"><SelectValue placeholder={t("Todos os módulos")}/></SelectTrigger><SelectContent><SelectItem value="todos">{t("Todos os módulos")}</SelectItem>{modules.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
    <Card><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>{t("Data e hora")}</TableHead><TableHead>{t("Usuário")}</TableHead><TableHead>{t("Perfil")}</TableHead><TableHead>{t("Ação")}</TableHead><TableHead>{t("Módulo")}</TableHead><TableHead>{t("Registro")}</TableHead><TableHead>{t("Origem")}</TableHead><TableHead className="w-16"/></TableRow></TableHeader><TableBody>{loading?<TableRow><TableCell colSpan={8} className="h-32 text-center">{t("Carregando...")}</TableCell></TableRow>:!rows.length?<TableRow><TableCell colSpan={8} className="h-32 text-center text-muted-foreground">{t("Nenhum evento encontrado no período.")}</TableCell></TableRow>:rows.map(r=><TableRow key={r.id}><TableCell className="whitespace-nowrap text-xs">{date(r.ocorrido_em,{dateStyle:"short",timeStyle:"medium"})}</TableCell><TableCell><p className="font-medium">{r.usuario_nome||t("Usuário não identificado")}</p><p className="text-xs text-muted-foreground">{r.usuario_email}</p></TableCell><TableCell>{r.usuario_perfil||"—"}</TableCell><TableCell><Badge className={actionTone[r.acao]||"bg-slate-100 text-slate-700"}>{r.acao}</Badge></TableCell><TableCell>{r.modulo}</TableCell><TableCell className="max-w-40 truncate font-mono text-xs">{r.registro_id||"—"}</TableCell><TableCell>{r.origem}</TableCell><TableCell><Button variant="ghost" size="icon" onClick={()=>setSelected(r)} aria-label={t("Ver detalhes")}><Eye className="h-4 w-4"/></Button></TableCell></TableRow>)}</TableBody></Table></div><p className="border-t px-4 py-3 text-xs text-muted-foreground">{rows.length} {t("eventos exibidos")}</p></CardContent></Card>
    <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-h-[85vh] max-w-3xl overflow-y-auto"><DialogHeader><DialogTitle>{t("Detalhes da auditoria")}</DialogTitle></DialogHeader>{selected&&<div className="space-y-4 text-sm"><div className="grid gap-2 sm:grid-cols-2"><p><b>{t("Usuário")}:</b> {selected.usuario_nome||selected.usuario_email||"—"}</p><p><b>{t("Data e hora")}:</b> {date(selected.ocorrido_em,{dateStyle:"long",timeStyle:"medium"})}</p><p><b>{t("Tabela")}:</b> {selected.tabela||"—"}</p><p><b>IP:</b> {selected.ip||"—"}</p></div><div><b>{t("Antes")}</b><pre className="mt-1 max-h-52 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(selected.dados_anteriores,null,2)||"—"}</pre></div><div><b>{t("Depois")}</b><pre className="mt-1 max-h-52 overflow-auto rounded bg-muted p-3 text-xs">{JSON.stringify(selected.dados_novos,null,2)||"—"}</pre></div></div>}</DialogContent></Dialog>
  </div></Layout>
}
