import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Layout } from "@/components/layout/Layout";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ShieldCheck, Plus, Users, KeyRound, Pencil, UserPlus, Trash2, CalendarClock, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { ComparacaoAba } from "@/components/controle-acesso/ComparacaoAba";
import { UsuariosAba } from "@/components/controle-acesso/UsuariosAba";
import { GovernancaAba } from "@/components/controle-acesso/GovernancaAba";

type Permission = { id:string; chave:string; modulo:string; acao:string; nome:string; sensivel:boolean };
type Profile = { id:string; nome:string; descricao:string|null; cor:string; sistema:boolean; ativo:boolean };
type User = { id:string; user_id:string|null; nome:string|null; email:string|null };
type Assignment = { id:string; user_id:string; profile_id:string; scope_type:string; scope_id:string|null; valido_ate:string|null; access_profiles?:{nome:string}|null };
type ScopeOption = { id:string; nome:string; departamento_id?:string };
type Delegation = { id:string; de_user_id:string; para_user_id:string; profile_id:string; inicio_em:string; fim_em:string; motivo:string; revogado_em:string|null; access_profiles?:{nome:string}|null };
type ApprovalLimit = { id:string; profile_id:string; modulo:string; limite:number; scope_type:string; access_profiles?:{nome:string}|null };
const actions = ["visualizar","criar","editar","excluir","aprovar","encerrar","exportar","administrar"];

export default function ControleAcesso(){
  const qc=useQueryClient();
  const [profileOpen,setProfileOpen]=useState(false); const [assignmentOpen,setAssignmentOpen]=useState(false);
  const [editing,setEditing]=useState<Profile|null>(null); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [selected,setSelected]=useState<Set<string>>(new Set());
  const [userId,setUserId]=useState(""); const [profileId,setProfileId]=useState(""); const [scope,setScope]=useState("empresa"); const [scopeId,setScopeId]=useState(""); const [expires,setExpires]=useState(""); const [justification,setJustification]=useState("");
  const [sectorOpen,setSectorOpen]=useState(false); const [sectorName,setSectorName]=useState(""); const [sectorDepartment,setSectorDepartment]=useState("");
  const [delegationOpen,setDelegationOpen]=useState(false); const [delegateFrom,setDelegateFrom]=useState(""); const [delegateTo,setDelegateTo]=useState(""); const [delegateProfile,setDelegateProfile]=useState(""); const [delegateStart,setDelegateStart]=useState(""); const [delegateEnd,setDelegateEnd]=useState(""); const [delegateReason,setDelegateReason]=useState("");
  const [limitOpen,setLimitOpen]=useState(false); const [limitProfile,setLimitProfile]=useState(""); const [limitModule,setLimitModule]=useState("financeiro"); const [limitValue,setLimitValue]=useState("");
  const {data,isLoading}=useQuery({queryKey:["access-control"],queryFn:async()=>{
    const [p,pr,link,u,a,d,o,s,dg,lm]=await Promise.all([
      (supabase as any).from("access_profiles").select("*").order("nome"),
      (supabase as any).from("access_permissions").select("*").order("modulo").order("acao"),
      (supabase as any).from("access_profile_permissions").select("profile_id,permission_id").eq("permitido",true),
      (supabase as any).from("profiles").select("id,user_id,nome,email").not("user_id","is",null).order("nome"),
      (supabase as any).from("employee_access_profiles").select("*,access_profiles(nome)").is("revogado_em",null).order("created_at",{ascending:false}),
      (supabase as any).from("departamentos").select("id,nome").order("nome"),
      (supabase as any).from("obras").select("id,nome").order("nome"),
      (supabase as any).from("departamento_setores").select("id,nome,departamento_id").eq("ativo",true).order("nome"),
      (supabase as any).from("access_delegations").select("*,access_profiles(nome)").order("created_at",{ascending:false}),
      (supabase as any).from("access_approval_limits").select("*,access_profiles(nome)").order("modulo"),
    ]);
    const error=[p,pr,link,u,a,d,o,s,dg,lm].find(x=>x.error)?.error; if(error) throw error;
    return {profiles:p.data as Profile[],permissions:pr.data as Permission[],links:link.data as {profile_id:string;permission_id:string}[],users:u.data as User[],assignments:a.data as Assignment[],departments:d.data as ScopeOption[],obras:o.data as ScopeOption[],sectors:s.data as ScopeOption[],delegations:dg.data as Delegation[],limits:lm.data as ApprovalLimit[]};
  }});
  useEffect(()=>{if(!profileOpen){setEditing(null);setName("");setDescription("");setSelected(new Set());}},[profileOpen]);
  const modules=useMemo(()=>Object.entries((data?.permissions??[]).reduce((acc:Record<string,Permission[]>,p)=>{(acc[p.modulo]??=[]).push(p);return acc;},{})),[data?.permissions]);
  const openEdit=(p:Profile)=>{setEditing(p);setName(p.nome);setDescription(p.descricao??"");setSelected(new Set((data?.links??[]).filter(x=>x.profile_id===p.id).map(x=>x.permission_id)));setProfileOpen(true)};
  const saveProfile=async()=>{try{if(!name.trim()) throw new Error("Informe o nome do perfil"); let id=editing?.id;
    if(id){const {error}=await (supabase as any).from("access_profiles").update({nome:name.trim(),descricao:description.trim()||null,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;await (supabase as any).from("access_profile_permissions").delete().eq("profile_id",id);}
    else {const {data:created,error}=await (supabase as any).from("access_profiles").insert({nome:name.trim(),descricao:description.trim()||null}).select("id").single();if(error)throw error;id=created.id;}
    if(selected.size){const {error}=await (supabase as any).from("access_profile_permissions").insert([...selected].map(permission_id=>({profile_id:id,permission_id,permitido:true})));if(error)throw error;}
    toast.success("Perfil salvo com sucesso");setProfileOpen(false);qc.invalidateQueries({queryKey:["access-control"]});
  }catch(e:any){toast.error(e.message??"Não foi possível salvar")}};
  const saveAssignment=async()=>{try{if(!userId||!profileId)throw new Error("Selecione o usuário e o perfil");if(!["empresa","proprio","equipe"].includes(scope)&&!scopeId)throw new Error("Selecione onde o acesso será válido");if(!justification.trim())throw new Error("Informe o motivo da concessão");const {error}=await (supabase as any).from("employee_access_profiles").insert({user_id:userId,profile_id:profileId,scope_type:scope,scope_id:scopeId||null,valido_ate:expires?new Date(expires+"T23:59:59").toISOString():null,justificativa:justification.trim()});if(error)throw error;toast.success("Acesso atribuído");setAssignmentOpen(false);setUserId("");setProfileId("");setScopeId("");setExpires("");setJustification("");qc.invalidateQueries({queryKey:["access-control"]});}catch(e:any){toast.error(e.message??"Não foi possível atribuir")}};
  // Revogar marca a data e quem revogou; a linha fica para o histórico de acessos.
  const removeAssignment=async(id:string)=>{if(!confirm("Revogar este acesso agora? A alteração ficará registrada na auditoria."))return;const {data:auth}=await supabase.auth.getUser();const {error}=await (supabase as any).from("employee_access_profiles").update({revogado_em:new Date().toISOString(),revogado_por:auth.user?.id??null}).eq("id",id);if(error)toast.error(error.message);else{toast.success("Acesso revogado");qc.invalidateQueries({queryKey:["access-control"]})}};
  const userName=(uid:string)=>{const u=data?.users.find(x=>x.user_id===uid);return u?.nome||u?.email||uid};
  const scopeName=(a:Assignment)=>{if(!a.scope_id)return a.scope_type;const list=a.scope_type==="obra"?data?.obras:a.scope_type==="setor"?data?.sectors:data?.departments;return `${a.scope_type}: ${list?.find(x=>x.id===a.scope_id)?.nome??"não encontrado"}`};
  const scopeOptions=scope==="obra"?data?.obras:scope==="setor"?data?.sectors:scope==="departamento"?data?.departments:[];
  const expiredCount=data?.assignments.filter(a=>a.valido_ate&&new Date(a.valido_ate)<=new Date()).length??0;
  const createReview=async()=>{const titulo=prompt("Nome da revisão de acessos:",`Revisão ${new Date().toLocaleDateString("pt-BR")}`);if(!titulo)return;const {error}=await (supabase as any).rpc("create_access_review",{p_titulo:titulo});if(error)toast.error(error.message);else{toast.success("Revisão criada com todos os acessos ativos");qc.invalidateQueries({queryKey:["access-governance"]})}};
  const saveSector=async()=>{if(!sectorName.trim()||!sectorDepartment){toast.error("Informe departamento e nome do setor");return}const {error}=await (supabase as any).from("departamento_setores").insert({departamento_id:sectorDepartment,nome:sectorName.trim()});if(error)toast.error(error.message);else{toast.success("Setor criado");setSectorOpen(false);setSectorName("");setSectorDepartment("");qc.invalidateQueries({queryKey:["access-control"]})}};
  const saveDelegation=async()=>{if(!delegateFrom||!delegateTo||!delegateProfile||!delegateStart||!delegateEnd||!delegateReason.trim()){toast.error("Preencha todos os dados da substituição");return}if(delegateFrom===delegateTo){toast.error("Origem e substituto precisam ser diferentes");return}const {error}=await (supabase as any).from("access_delegations").insert({de_user_id:delegateFrom,para_user_id:delegateTo,profile_id:delegateProfile,inicio_em:new Date(delegateStart).toISOString(),fim_em:new Date(delegateEnd).toISOString(),motivo:delegateReason.trim()});if(error)toast.error(error.message);else{toast.success("Substituição programada");setDelegationOpen(false);qc.invalidateQueries({queryKey:["access-control"]})}};
  const saveLimit=async()=>{const value=Number(limitValue.replace(",","."));if(!limitProfile||!limitModule||!Number.isFinite(value)||value<0){toast.error("Informe perfil, módulo e limite válido");return}const {error}=await (supabase as any).from("access_approval_limits").insert({profile_id:limitProfile,modulo:limitModule,limite:value,scope_type:"empresa"});if(error)toast.error(error.message);else{toast.success("Limite configurado");setLimitOpen(false);qc.invalidateQueries({queryKey:["access-control"]})}};
  return <Layout><div className="mx-auto max-w-screen-xl space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="h-6 w-6 text-primary"/>Controle de Acesso</h1><p className="text-sm text-muted-foreground">Perfis, ações, escopos e acessos temporários com rastreabilidade.</p></div></div>
    <div className="grid gap-3 md:grid-cols-4"><Card><CardContent className="flex items-center gap-3 p-4"><KeyRound className="text-primary"/><div><b className="text-2xl">{data?.profiles.length??0}</b><p className="text-xs text-muted-foreground">Perfis configurados</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><Users className="text-primary"/><div><b className="text-2xl">{new Set(data?.assignments.map(x=>x.user_id)).size||0}</b><p className="text-xs text-muted-foreground">Usuários com perfil</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><ShieldCheck className="text-primary"/><div><b className="text-2xl">{data?.permissions.length??0}</b><p className="text-xs text-muted-foreground">Permissões por ação</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><AlertTriangle className={expiredCount?"text-amber-600":"text-emerald-600"}/><div><b className="text-2xl">{expiredCount}</b><p className="text-xs text-muted-foreground">Acessos expirados</p></div></CardContent></Card></div>
    <Tabs defaultValue="users"><div className="flex flex-wrap items-center justify-between gap-2"><TabsList className="h-auto flex-wrap"><TabsTrigger value="users">Usuários</TabsTrigger><TabsTrigger value="profiles">Perfis</TabsTrigger><TabsTrigger value="governance">Governança</TabsTrigger><TabsTrigger value="delegations">Substituições</TabsTrigger><TabsTrigger value="limits">Limites</TabsTrigger><TabsTrigger value="matrix">Matriz</TabsTrigger><TabsTrigger value="compare">Comparação</TabsTrigger></TabsList><Button variant="outline" size="sm" onClick={createReview}><CalendarClock className="mr-2 h-4 w-4"/>Iniciar revisão de acessos</Button></div>
      <TabsContent value="profiles"><div className="mb-3 flex justify-end"><Button size="sm" onClick={()=>setProfileOpen(true)}><Plus className="mr-2 h-4 w-4"/>Novo perfil</Button></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{isLoading?<p>Carregando...</p>:data?.profiles.map(p=><Card key={p.id}><CardHeader className="pb-2"><div className="flex justify-between gap-2"><CardTitle className="text-base">{p.nome}</CardTitle><Button size="icon" variant="ghost" onClick={()=>openEdit(p)}><Pencil className="h-4 w-4"/></Button></div></CardHeader><CardContent><p className="min-h-10 text-sm text-muted-foreground">{p.descricao||"Sem descrição"}</p><div className="mt-3 flex gap-2"><Badge variant="secondary">{data.links.filter(x=>x.profile_id===p.id).length} permissões</Badge>{p.sistema&&<Badge variant="outline">Padrão</Badge>}</div></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="users"><UsuariosAba/></TabsContent>
      <TabsContent value="governance"><GovernancaAba/></TabsContent>
      <TabsContent value="delegations"><div className="mb-3 flex justify-end"><Button size="sm" onClick={()=>setDelegationOpen(true)}><Plus className="mr-2 h-4 w-4"/>Nova substituição</Button></div><Card><CardContent className="p-0"><div className="divide-y">{data?.delegations.map(d=><div key={d.id} className="grid gap-2 p-4 md:grid-cols-4"><div><b>{userName(d.para_user_id)}</b><p className="text-xs text-muted-foreground">substitui {userName(d.de_user_id)}</p></div><div>{d.access_profiles?.nome}</div><div className="text-sm">{new Date(d.inicio_em).toLocaleDateString("pt-BR")} → {new Date(d.fim_em).toLocaleDateString("pt-BR")}</div><Badge variant={d.revogado_em?"secondary":"outline"} className="w-fit">{d.revogado_em?"Revogada":"Programada"}</Badge></div>)}{!data?.delegations.length&&<p className="p-8 text-center text-muted-foreground">Nenhuma substituição programada.</p>}</div></CardContent></Card></TabsContent>
      <TabsContent value="limits"><div className="mb-3 flex justify-end"><Button size="sm" onClick={()=>setLimitOpen(true)}><Plus className="mr-2 h-4 w-4"/>Novo limite</Button></div><Card><CardContent className="p-0"><div className="divide-y">{data?.limits.map(l=><div key={l.id} className="grid gap-2 p-4 md:grid-cols-3"><b>{l.access_profiles?.nome}</b><span className="capitalize">{l.modulo.replaceAll("_"," ")}</span><span className="font-semibold text-emerald-700">{Number(l.limite).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</span></div>)}{!data?.limits.length&&<p className="p-8 text-center text-muted-foreground">Nenhum limite de aprovação definido.</p>}</div></CardContent></Card></TabsContent>
      <TabsContent value="matrix"><Card><CardContent className="overflow-auto p-0"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/50"><th className="p-3 text-left">Módulo</th>{actions.map(a=><th className="p-3 text-center" key={a}>{a}</th>)}</tr></thead><tbody>{modules.map(([m,ps])=><tr className="border-b" key={m}><td className="p-3 font-medium">{m.replaceAll("_"," ")}</td>{actions.map(a=><td className="p-3 text-center" key={a}>{ps.some(p=>p.acao===a)?"✓":"—"}</td>)}</tr>)}</tbody></table></CardContent></Card></TabsContent>
      <TabsContent value="compare"><ComparacaoAba/></TabsContent>
    </Tabs>
    <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="max-h-[90vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{editing?"Editar perfil":"Novo perfil de acesso"}</DialogTitle></DialogHeader><div className="grid gap-3 md:grid-cols-2"><div><Label>Nome</Label><Input value={name} onChange={e=>setName(e.target.value)}/></div><div><Label>Descrição</Label><Input value={description} onChange={e=>setDescription(e.target.value)}/></div></div><div className="space-y-4">{modules.map(([m,ps])=><div key={m} className="rounded-lg border p-3"><b className="capitalize">{m.replaceAll("_"," ")}</b><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-4">{ps.map(p=><label className="flex items-center gap-2 text-sm" key={p.id}><Checkbox checked={selected.has(p.id)} onCheckedChange={v=>setSelected(s=>{const n=new Set(s);if(v){n.add(p.id)}else{n.delete(p.id)}return n})}/>{p.acao}{p.sensivel&&<span title="Dado sensível">*</span>}</label>)}</div></div>)}</div><DialogFooter><Button variant="outline" onClick={()=>setProfileOpen(false)}>Cancelar</Button><Button onClick={saveProfile}>Salvar perfil</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={delegationOpen} onOpenChange={setDelegationOpen}><DialogContent><DialogHeader><DialogTitle>Substituição temporária</DialogTitle></DialogHeader><div className="grid gap-3"><div><Label>Titular</Label><Select value={delegateFrom} onValueChange={setDelegateFrom}><SelectTrigger><SelectValue placeholder="Quem será substituído"/></SelectTrigger><SelectContent>{data?.users.map(u=><SelectItem key={u.id} value={u.user_id!}>{u.nome||u.email}</SelectItem>)}</SelectContent></Select></div><div><Label>Substituto</Label><Select value={delegateTo} onValueChange={setDelegateTo}><SelectTrigger><SelectValue placeholder="Quem assumirá"/></SelectTrigger><SelectContent>{data?.users.map(u=><SelectItem key={u.id} value={u.user_id!}>{u.nome||u.email}</SelectItem>)}</SelectContent></Select></div><div><Label>Perfil delegado</Label><Select value={delegateProfile} onValueChange={setDelegateProfile}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{data?.profiles.map(p=><SelectItem key={p.id} value={p.id}>{p.nome}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div><Label>Início</Label><Input type="datetime-local" value={delegateStart} onChange={e=>setDelegateStart(e.target.value)}/></div><div><Label>Fim</Label><Input type="datetime-local" value={delegateEnd} onChange={e=>setDelegateEnd(e.target.value)}/></div></div><div><Label>Motivo</Label><Input value={delegateReason} onChange={e=>setDelegateReason(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setDelegationOpen(false)}>Cancelar</Button><Button onClick={saveDelegation}>Programar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={limitOpen} onOpenChange={setLimitOpen}><DialogContent><DialogHeader><DialogTitle>Limite de aprovação</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Perfil aprovador</Label><Select value={limitProfile} onValueChange={setLimitProfile}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{data?.profiles.map(p=><SelectItem key={p.id} value={p.id}>{p.nome}</SelectItem>)}</SelectContent></Select></div><div><Label>Módulo</Label><Select value={limitModule} onValueChange={setLimitModule}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["financeiro","fundo_fixo","almoxarifado","subcontratadas"].map(m=><SelectItem key={m} value={m}>{m.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Valor máximo</Label><Input type="number" min="0" step="0.01" value={limitValue} onChange={e=>setLimitValue(e.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={()=>setLimitOpen(false)}>Cancelar</Button><Button onClick={saveLimit}>Salvar limite</Button></DialogFooter></DialogContent></Dialog>
  </div></Layout>;
}
