-- Diferencia consumo de itens retornaveis e cria o ciclo de devolucao.
ALTER TABLE public.materiais_catalogo
  ADD COLUMN IF NOT EXISTS tipo_item text NOT NULL DEFAULT 'consumo';
ALTER TABLE public.materiais_catalogo DROP CONSTRAINT IF EXISTS materiais_catalogo_tipo_item_check;
ALTER TABLE public.materiais_catalogo ADD CONSTRAINT materiais_catalogo_tipo_item_check
  CHECK (tipo_item IN ('consumo','retornavel'));

ALTER TABLE public.almoxarifado_entrega_itens
  ADD COLUMN IF NOT EXISTS retornavel boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS quantidade_devolvida numeric(14,3) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.almoxarifado_devolucoes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  numero bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  obra_id uuid NOT NULL REFERENCES public.obras(id),
  funcionario_id uuid NOT NULL REFERENCES public.employees(id),
  recebido_por uuid NOT NULL REFERENCES public.employees(id),
  observacoes text,
  dispositivo_id text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.almoxarifado_devolucao_itens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  devolucao_id uuid NOT NULL REFERENCES public.almoxarifado_devolucoes(id) ON DELETE RESTRICT,
  entrega_item_id uuid NOT NULL REFERENCES public.almoxarifado_entrega_itens(id),
  material_id uuid NOT NULL REFERENCES public.materiais_catalogo(id),
  quantidade numeric(14,3) NOT NULL CHECK (quantidade > 0),
  condicao text NOT NULL DEFAULT 'bom' CHECK (condicao IN ('bom','avariado','inutilizado')),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.almoxarifado_movimentos
  ADD COLUMN IF NOT EXISTS devolucao_id uuid REFERENCES public.almoxarifado_devolucoes(id);

ALTER TABLE public.almoxarifado_devolucoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.almoxarifado_devolucao_itens ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS almox_devolucoes_obra_data_idx ON public.almoxarifado_devolucoes(obra_id, created_at DESC);

DROP POLICY IF EXISTS almox_devolucoes_select_scoped ON public.almoxarifado_devolucoes;
CREATE POLICY almox_devolucoes_select_scoped ON public.almoxarifado_devolucoes FOR SELECT TO authenticated
USING (public.can_manage_obra_data(obra_id) OR recebido_por = (SELECT id FROM public.employees WHERE user_id = auth.uid() LIMIT 1));
DROP POLICY IF EXISTS almox_devolucao_itens_select_scoped ON public.almoxarifado_devolucao_itens;
CREATE POLICY almox_devolucao_itens_select_scoped ON public.almoxarifado_devolucao_itens FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM public.almoxarifado_devolucoes d WHERE d.id = devolucao_id AND (public.can_manage_obra_data(d.obra_id) OR d.recebido_por = (SELECT id FROM public.employees WHERE user_id = auth.uid() LIMIT 1))));

CREATE OR REPLACE FUNCTION public.listar_funcionarios_app_almoxarifado()
RETURNS TABLE(id uuid, nome text, cargo text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth, pg_temp AS $$
DECLARE v_operador uuid; v_obra uuid; v_total int;
BEGIN
  IF NOT public.has_employee_app_access('almoxarifado') THEN RAISE EXCEPTION 'Acesso nao autorizado.'; END IF;
  SELECT e.id INTO v_operador FROM public.employees e WHERE e.user_id = auth.uid() LIMIT 1;
  SELECT count(DISTINCT ofu.obra_id), min(ofu.obra_id) INTO v_total, v_obra FROM public.obra_funcionarios ofu
    WHERE ofu.employee_id = v_operador AND ofu.status = true AND (ofu.data_saida IS NULL OR ofu.data_saida >= CURRENT_DATE);
  IF v_total <> 1 THEN RAISE EXCEPTION 'O operador deve possuir exatamente uma obra ativa.'; END IF;
  RETURN QUERY SELECT e.id, e.nome, c.nome FROM public.obra_funcionarios ofu
    JOIN public.employees e ON e.id = ofu.employee_id LEFT JOIN public.cargos c ON c.id = e.cargo_id
    WHERE ofu.obra_id = v_obra AND ofu.status = true AND e.status = 'ativo'
      AND (ofu.data_saida IS NULL OR ofu.data_saida >= CURRENT_DATE) ORDER BY e.nome;
END; $$;
REVOKE ALL ON FUNCTION public.listar_funcionarios_app_almoxarifado() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.listar_funcionarios_app_almoxarifado() TO authenticated;

CREATE OR REPLACE FUNCTION public.listar_responsabilidades_almoxarifado(p_funcionario_id uuid)
RETURNS TABLE(entrega_item_id uuid, material_id uuid, material_nome text, unidade text, quantidade_pendente numeric)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth, pg_temp AS $$
DECLARE v_operador uuid; v_obra uuid;
BEGIN
  IF NOT public.has_employee_app_access('almoxarifado') THEN RAISE EXCEPTION 'Acesso nao autorizado.'; END IF;
  SELECT e.id INTO v_operador FROM public.employees e WHERE e.user_id = auth.uid() LIMIT 1;
  SELECT ofu.obra_id INTO v_obra FROM public.obra_funcionarios ofu WHERE ofu.employee_id = v_operador AND ofu.status = true LIMIT 1;
  RETURN QUERY SELECT ei.id, ei.material_id, m.nome, m.unidade, ei.quantidade - ei.quantidade_devolvida
    FROM public.almoxarifado_entrega_itens ei
    JOIN public.almoxarifado_entregas en ON en.id = ei.entrega_id
    JOIN public.materiais_catalogo m ON m.id = ei.material_id
    WHERE en.obra_id = v_obra AND en.retirado_por = p_funcionario_id AND ei.retornavel
      AND ei.quantidade > ei.quantidade_devolvida AND en.status = 'confirmada'
    ORDER BY en.created_at, m.nome;
END; $$;
REVOKE ALL ON FUNCTION public.listar_responsabilidades_almoxarifado(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.listar_responsabilidades_almoxarifado(uuid) TO authenticated;

-- Marca automaticamente a natureza do item no momento da entrega.
CREATE OR REPLACE FUNCTION public.fn_marcar_item_entrega_retornavel()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
  SELECT tipo_item = 'retornavel' INTO NEW.retornavel FROM public.materiais_catalogo WHERE id = NEW.material_id;
  RETURN NEW;
END; $$;
DROP TRIGGER IF EXISTS trg_marcar_item_entrega_retornavel ON public.almoxarifado_entrega_itens;
CREATE TRIGGER trg_marcar_item_entrega_retornavel BEFORE INSERT ON public.almoxarifado_entrega_itens
FOR EACH ROW EXECUTE FUNCTION public.fn_marcar_item_entrega_retornavel();

CREATE OR REPLACE FUNCTION public.registrar_devolucao_almoxarifado(
  p_funcionario_id uuid, p_observacoes text, p_dispositivo_id text, p_itens jsonb
) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, auth, pg_temp AS $$
DECLARE v_operador uuid; v_obra uuid; v_total int; v_devolucao uuid; item jsonb; v_entrega_item public.almoxarifado_entrega_itens%ROWTYPE; v_qtd numeric; v_condicao text;
BEGIN
  IF NOT public.has_employee_app_access('almoxarifado') THEN RAISE EXCEPTION 'Acesso nao autorizado.'; END IF;
  IF p_itens IS NULL OR jsonb_array_length(p_itens) = 0 THEN RAISE EXCEPTION 'Selecione ao menos um item.'; END IF;
  SELECT e.id INTO v_operador FROM public.employees e WHERE e.user_id = auth.uid() LIMIT 1;
  SELECT count(DISTINCT ofu.obra_id), min(ofu.obra_id) INTO v_total, v_obra FROM public.obra_funcionarios ofu WHERE ofu.employee_id = v_operador AND ofu.status = true;
  IF v_total <> 1 THEN RAISE EXCEPTION 'O operador deve possuir exatamente uma obra ativa.'; END IF;
  INSERT INTO public.almoxarifado_devolucoes(obra_id, funcionario_id, recebido_por, observacoes, dispositivo_id)
    VALUES(v_obra, p_funcionario_id, v_operador, nullif(trim(p_observacoes),''), nullif(trim(p_dispositivo_id),'')) RETURNING id INTO v_devolucao;
  FOR item IN SELECT value FROM jsonb_array_elements(p_itens) LOOP
    SELECT * INTO v_entrega_item FROM public.almoxarifado_entrega_itens WHERE id = (item->>'entrega_item_id')::uuid FOR UPDATE;
    v_qtd := (item->>'quantidade')::numeric; v_condicao := COALESCE(item->>'condicao','bom');
    IF v_qtd <= 0 OR NOT v_entrega_item.retornavel OR v_qtd > v_entrega_item.quantidade - v_entrega_item.quantidade_devolvida THEN RAISE EXCEPTION 'Quantidade de devolucao invalida.'; END IF;
    IF NOT EXISTS (SELECT 1 FROM public.almoxarifado_entregas en WHERE en.id = v_entrega_item.entrega_id AND en.obra_id = v_obra AND en.retirado_por = p_funcionario_id) THEN RAISE EXCEPTION 'Item nao pertence ao funcionario desta obra.'; END IF;
    INSERT INTO public.almoxarifado_devolucao_itens(devolucao_id,entrega_item_id,material_id,quantidade,condicao) VALUES(v_devolucao,v_entrega_item.id,v_entrega_item.material_id,v_qtd,v_condicao);
    UPDATE public.almoxarifado_entrega_itens SET quantidade_devolvida = quantidade_devolvida + v_qtd WHERE id = v_entrega_item.id;
    IF v_condicao = 'bom' THEN
      INSERT INTO public.almoxarifado_movimentos(obra_id,material_id,tipo,quantidade,observacoes,registrado_por,data_movimento,devolucao_id)
      VALUES(v_obra,v_entrega_item.material_id,'entrada',v_qtd,'Devolucao de item retornavel',auth.uid(),CURRENT_DATE,v_devolucao);
    END IF;
  END LOOP;
  RETURN v_devolucao;
END; $$;
REVOKE ALL ON FUNCTION public.registrar_devolucao_almoxarifado(uuid,text,text,jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.registrar_devolucao_almoxarifado(uuid,text,text,jsonb) TO authenticated;
