-- App Almoxarifado: entregas assinadas e baixas atomicas por obra vinculada.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.almoxarifado_entregas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  numero bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  obra_id uuid NOT NULL REFERENCES public.obras(id),
  retirado_por uuid NOT NULL REFERENCES public.employees(id),
  entregue_por uuid NOT NULL REFERENCES public.employees(id),
  frente text NOT NULL,
  finalidade text,
  observacoes text,
  assinatura_base64 text NOT NULL,
  assinatura_hash text NOT NULL,
  assinado_em timestamptz NOT NULL DEFAULT now(),
  dispositivo_id text,
  status text NOT NULL DEFAULT 'confirmada' CHECK (status IN ('confirmada','estornada')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.almoxarifado_entrega_itens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entrega_id uuid NOT NULL REFERENCES public.almoxarifado_entregas(id) ON DELETE RESTRICT,
  material_id uuid NOT NULL REFERENCES public.materiais_catalogo(id),
  quantidade numeric(14,3) NOT NULL CHECK (quantidade > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (entrega_id, material_id)
);

ALTER TABLE public.almoxarifado_movimentos
  ADD COLUMN IF NOT EXISTS entrega_id uuid REFERENCES public.almoxarifado_entregas(id);

CREATE INDEX IF NOT EXISTS almox_entregas_obra_data_idx
  ON public.almoxarifado_entregas(obra_id, created_at DESC);
CREATE INDEX IF NOT EXISTS almox_entregas_retirado_idx
  ON public.almoxarifado_entregas(retirado_por, created_at DESC);
CREATE INDEX IF NOT EXISTS almox_entrega_itens_entrega_idx
  ON public.almoxarifado_entrega_itens(entrega_id);

ALTER TABLE public.almoxarifado_entregas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.almoxarifado_entrega_itens ENABLE ROW LEVEL SECURITY;

-- O almoxarife ve somente o saldo da obra em que esta vinculado.
DROP POLICY IF EXISTS almox_estoque_app_select ON public.almoxarifado_estoque;
CREATE POLICY almox_estoque_app_select ON public.almoxarifado_estoque
  FOR SELECT TO authenticated USING (
    obra_id = ANY(COALESCE(public.get_user_obra_ids(), ARRAY[]::uuid[]))
  );

DROP POLICY IF EXISTS almox_entregas_select_scoped ON public.almoxarifado_entregas;
CREATE POLICY almox_entregas_select_scoped ON public.almoxarifado_entregas
  FOR SELECT TO authenticated USING (
    public.can_manage_obra_data(obra_id)
    OR entregue_por = (SELECT id FROM public.employees WHERE user_id = auth.uid() LIMIT 1)
  );

DROP POLICY IF EXISTS almox_entrega_itens_select_scoped ON public.almoxarifado_entrega_itens;
CREATE POLICY almox_entrega_itens_select_scoped ON public.almoxarifado_entrega_itens
  FOR SELECT TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.almoxarifado_entregas entrega
      WHERE entrega.id = entrega_id
        AND (
          public.can_manage_obra_data(entrega.obra_id)
          OR entrega.entregue_por = (SELECT id FROM public.employees WHERE user_id = auth.uid() LIMIT 1)
        )
    )
  );

CREATE OR REPLACE FUNCTION public.registrar_entrega_almoxarifado(
  p_retirado_por uuid,
  p_frente text,
  p_finalidade text,
  p_observacoes text,
  p_assinatura_base64 text,
  p_dispositivo_id text,
  p_itens jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  operador_id uuid;
  obra_vinculada_id uuid;
  total_obras integer;
  entrega_id uuid;
  item jsonb;
  material_id uuid;
  quantidade numeric(14,3);
  itens_normalizados text;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'Usuario nao autenticado.'; END IF;

  SELECT id INTO operador_id FROM public.employees WHERE user_id = auth.uid() LIMIT 1;
  IF operador_id IS NULL THEN RAISE EXCEPTION 'Usuario sem cadastro de funcionario.'; END IF;

  SELECT count(DISTINCT ofu.obra_id), min(ofu.obra_id::text)::uuid
    INTO total_obras, obra_vinculada_id
  FROM public.obra_funcionarios ofu
  WHERE ofu.employee_id = operador_id AND ofu.status = true
    AND (ofu.data_saida IS NULL OR ofu.data_saida >= CURRENT_DATE);

  IF total_obras = 0 THEN RAISE EXCEPTION 'Funcionario sem obra ativa vinculada.'; END IF;
  IF total_obras > 1 THEN RAISE EXCEPTION 'Funcionario possui mais de uma obra ativa. Regularize o vinculo antes de usar o app.'; END IF;
  IF nullif(trim(p_frente), '') IS NULL THEN RAISE EXCEPTION 'Informe a frente de servico.'; END IF;
  IF p_assinatura_base64 IS NULL OR length(p_assinatura_base64) < 100 THEN RAISE EXCEPTION 'Assinatura obrigatoria.'; END IF;
  IF p_itens IS NULL OR jsonb_typeof(p_itens) <> 'array' OR jsonb_array_length(p_itens) = 0 THEN RAISE EXCEPTION 'Adicione ao menos um material.'; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.obra_funcionarios
    WHERE obra_id = obra_vinculada_id AND employee_id = p_retirado_por AND status = true
      AND (data_saida IS NULL OR data_saida >= CURRENT_DATE)
  ) THEN RAISE EXCEPTION 'O funcionario que esta retirando nao pertence a esta obra.'; END IF;

  SELECT string_agg(
    (value->>'material_id') || ':' || (value->>'quantidade'), ',' ORDER BY value->>'material_id'
  ) INTO itens_normalizados FROM jsonb_array_elements(p_itens);

  INSERT INTO public.almoxarifado_entregas (
    obra_id, retirado_por, entregue_por, frente, finalidade, observacoes,
    assinatura_base64, assinatura_hash, dispositivo_id
  ) VALUES (
    obra_vinculada_id, p_retirado_por, operador_id, trim(p_frente),
    nullif(trim(p_finalidade), ''), nullif(trim(p_observacoes), ''),
    p_assinatura_base64,
    encode(digest(
      p_assinatura_base64 || itens_normalizados || p_retirado_por::text
      || operador_id::text || obra_vinculada_id::text || trim(p_frente),
      'sha256'
    ), 'hex'),
    nullif(trim(p_dispositivo_id), '')
  ) RETURNING id INTO entrega_id;

  FOR item IN SELECT value FROM jsonb_array_elements(p_itens) LOOP
    material_id := (item->>'material_id')::uuid;
    quantidade := (item->>'quantidade')::numeric;
    IF quantidade IS NULL OR quantidade <= 0 THEN RAISE EXCEPTION 'Quantidade de material invalida.'; END IF;

    INSERT INTO public.almoxarifado_entrega_itens(entrega_id, material_id, quantidade)
    VALUES (entrega_id, material_id, quantidade);

    INSERT INTO public.almoxarifado_movimentos (
      obra_id, material_id, tipo, quantidade, frente, observacoes,
      registrado_por, data_movimento, entrega_id
    ) VALUES (
      obra_vinculada_id, material_id, 'saida', quantidade, trim(p_frente),
      'Entrega assinada no balcao', auth.uid(), CURRENT_DATE, entrega_id
    );
  END LOOP;

  RETURN entrega_id;
END;
$$;

REVOKE ALL ON FUNCTION public.registrar_entrega_almoxarifado(uuid,text,text,text,text,text,jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.registrar_entrega_almoxarifado(uuid,text,text,text,text,text,jsonb) TO authenticated;
